/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    AppPostFooter: typeof import('./components/AppPostFooter.vue')['default']
    AppPostList: typeof import('./components/AppPostList.vue')['default']
    AppRouteLinks: typeof import('./components/AppRouteLinks.vue')['default']
    MarkdownShiki: typeof import('./components/MarkdownShiki.vue')['default']
    NeteaseMusicCard: typeof import('./components/NeteaseMusicCard.vue')['default']
    NeteaseMusicCardV2: typeof import('./components/NeteaseMusicCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaterColorBackground: typeof import('./components/WaterColorBackground.vue')['default']
  }
}
