/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./components/A.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    MarkdownWrapper: typeof import('./components/MarkdownWrapper.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
