/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/BaseHeader.vue')['default']
    MarkdownShiki: typeof import('./components/MarkdownShiki.vue')['default']
    NeteaseMusicCard: typeof import('./components/NeteaseMusicCard.vue')['default']
    PageIndexLinks: typeof import('./components/PageIndexLinks.vue')['default']
    PagePostsList: typeof import('./components/PagePostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaterColorBackground: typeof import('./components/WaterColorBackground.vue')['default']
  }
}
